# Created using wingetcreate 1.9.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: com.malawarecreator.neofile
PackageVersion: 0.0.0.1
PackageLocale: en-US
Publisher: benliu
PackageName: neofile
License: MIT License
ShortDescription: linux file command revived for windows
ManifestType: defaultLocale
ManifestVersion: 1.9.0
