# Created using wingetcreate 1.9.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: com.malawarecreator.neofile
PackageVersion: 0.0.0.1
InstallerType: portable
Commands:
- neofile
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/malawarecreator/neofile/raw/refs/heads/master/neofile.exe
  InstallerSha256: 87116DD5936C3BE13F9A03AEF9C10C4CC2E0EB797EB01EF6B56249F142E1A985
ManifestType: installer
ManifestVersion: 1.9.0
