# Created using wingetcreate 1.9.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: redis_password_manager.redis_password_manager
PackageVersion: 0.0.0.1
InstallerType: portable
Commands:
- redis_password_manager
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/malawarecreator/redis_password_manager/releases/download/v0.1/redis_password_manager.exe
  InstallerSha256: 10E10A078B92869E3C39597C697F947EC0FB023D4362D65360D01F25B32BF307
ManifestType: installer
ManifestVersion: 1.9.0
